# Generated by Django 3.1 on 2020-08-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
